entry:
  build: entry/
  ports:
    - "49400:80"
  links:
    - rabbitmq

board:
  build: board/
  links:
    - rabbitmq

pattern:
  build: pattern/
  ports:
      - "8082:80"
  links:
    - rabbitmq

mostsolved:
  build: most-solved/
  links:
    - rabbitmq
    - dictionary
    - pattern

dictionary:
  build: dictionary/
  ports:
      - "8081:80"

rabbitmq:
  image: rabbitmq 

elasticsearch:
  image: deviantony/elk-elasticsearch
  ports:
    - "9200:9200"

logstash:
  image: deviantony/elk-logstash
  volumes:
    - logstash-conf:/etc/logstash/conf.d
  ports:
    - "5000:5000"  
  links:
    - elasticsearch
    - rabbitmq

kibana3:
  image: deviantony/elk-kibana:kibana3
  ports:
    - "8080:80"
  links:
    - elasticsearch

kibana4:
  image: deviantony/elk-kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
